version: "3"

services:
    python:
        build: ./src
        working_dir: /github
        volumes:
            - ./src:/github
            - ../data/step_1_3_StackUsersOutFullStack.csv:/github/in/input.csv
            - ./out:/github/out
        command:  /bin/sh -c "chmod +x ./start.sh && ./start.sh" 